TechBlogWeb/Areas/Admin/Controllers/ArticleItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Entites;

namespace TechBlogWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="admin")]
    public class ArticleItemController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostEnvironment;

        public ArticleItemController(DataManager dataManager, IWebHostEnvironment hostEnvironment)
        {
            this.dataManager = dataManager;
            this.hostEnvironment = hostEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new Article() : dataManager.Articles.GetArticleById(id);
            ViewBag.Tags = new SelectList(dataManager.Articles
                                            .GetArticles()
                                            .Select(a => a.NormalizedTag)
                                            .Distinct());
            return View(entity);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Article model, IFormFile titleImagePath)
        {
            if (ModelState.IsValid)
            {
                if (titleImagePath != null)
                {
                    model.TitleImagePath = titleImagePath.FileName;
                    using (var stream = new FileStream(Path.Combine(hostEnvironment.WebRootPath, "images/", titleImagePath.FileName), FileMode.Create))
                    {
                        titleImagePath.CopyTo(stream);
                    }
                }
                model.Tag = model.NormalizedTag.Replace(" ", "");
                await dataManager.Articles.SaveArticleAsync(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
            }
            return View(model);
        }
    }
}

TechBlogWeb/Areas/Admin/Views/ArticleItem/Edit.cshtml
@model Article
@{
}
<div class="container">
	<div class="section first-section">

		<div>
			<form asp-area="Admin" asp-controller="ArticleItem" asp-action="Edit" method="post" enctype="multipart/form-data">
				<div asp-validation-summary="All"></div>

				<input asp-for="Id" type="hidden" />
				<input asp-for="DateTime" type="hidden" />
				<input asp-for="TitleImagePath" type="hidden" />

				<div>
					<label asp-for="NormalizedTag"></label>
					<select asp-for="NormalizedTag" asp-items="ViewBag.Tags"></select>					
					<span asp-validation-for="NormalizedTag"></span>
				</div>
				<div>
					<label asp-for="Title"></label>
					<input asp-for="Title" />
					<span asp-validation-for="Title"></span>
				</div>
				<div>
					<label asp-for="Text"></label>
					<textarea asp-for="Text"></textarea>
					<span asp-validation-for="Text"></span>
				</div>
				<div>
					<label asp-for="SubTitle"></label>
					<input asp-for="SubTitle" />
					<span asp-validation-for="SubTitle"></span>
				</div>
				<div>
					<label asp-for="Author"></label>
					<input asp-for="Author" />
					<span asp-validation-for="Author"></span>
				</div>
				<div>
					<label asp-for="TitleImagePath"></label>
					<input type="file" name="titleImagePath" id="titleImagePath" />
					<div>
						<img src="~/images/@Model.TitleImagePath" class="img-fluid" />
					</div>
				</div>
				<div>
					<label asp-for="MetaTitle"></label>
					<input asp-for="MetaTitle" />
					<span asp-validation-for="MetaTitle"></span>
				</div>
				<div>
					<label asp-for="MetaDescription"></label>
					<input asp-for="MetaDescription" />
					<span asp-validation-for="MetaDescription"></span>
				</div>
				<div>
					<label asp-for="MetaKeywords"></label>
					<input asp-for="MetaKeywords" />
					<span asp-validation-for="MetaKeywords"></span>
				</div>
				<input type="submit" value="Сохранить" />
			</form>
		</div>
	</div>
</div>

<script src="~/js/ckeditor/ckeditor.js"></script>
<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>