TechBlogWeb/Areas/Admin/Components/NavigatorTagViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechBlogWeb.Domain;

namespace TechBlogWeb.Areas.Admin.Components
{
    public class NavigatorTagViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public NavigatorTagViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            return View(model: dataManager.Articles
                .GetArticles()
                .Select(a => a.Tag)
                .Distinct());
        }
    }
}

TechBlogWeb/Areas/User/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TechBlogWeb.Areas.User.Models.ViewModels;

namespace TechBlogWeb.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "user")]
    public class ProfileController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;

        public ProfileController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            if (user != null)
            {
                var roles = await userManager.GetRolesAsync(user);
                return View(model: new UserProfileViewModel
                {
                    Roles = roles
                });
            }
            return View();
        }
    }
}

TechBlogWeb/Components/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TechBlogWeb.Components
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TechBlogWeb/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TechBlogWeb/Components/MainSectionViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class MainSectionViewComponent : ViewComponent
    {
        readonly DataManager dataManager;
        public MainSectionViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            //Выборка лучших за неделю (in progress)
            var week = DateTime.UtcNow.AddDays(-7);
            var model = dataManager.Articles.GetArticles().Where(a => a.DateTime.CompareTo(week) == 1).ToList();
            return View(model: model);
        }
    }
}

TechBlogWeb/Components/NewsDropViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class NewsDropViewComponent : ViewComponent
    {
        readonly DataManager dataManager;
        public NewsDropViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            var model = dataManager.Articles.GetArticles().OrderBy(a => a.Tag)
                .ThenByDescending(a => a.DateTime);
            return View(model: model);
        }
    }
}

TechBlogWeb/Components/RecentNewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechBlogWeb.Domain;
using TechBlogWeb.Models;
using TechBlogWeb.Models.ViewModel;

namespace TechBlogWeb.Components
{
    public class RecentNewsViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;
        private int pageSize = 10;

        public RecentNewsViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            object articlePage = 1;
            if (Request.RouteValues.ContainsKey("articlePage"))
            {
                Request.RouteValues.TryGetValue("articlePage", out articlePage);
            }
            var aP = int.Parse(articlePage.ToString());
            return View(model: new ArticleListViewModel()
            {
                Articles = dataManager.Articles.GetArticles()
                    .OrderByDescending(a => a.DateTime)
                    .Skip((aP - 1) * pageSize)
                    .Take(10)
                    .ToList(),
                PageInfo = new PageInfo
                {
                    ArticlePerPage = pageSize,
                    CurrentPage = aP,
                    TotalArticle = dataManager.Articles.GetArticles().Count()
                }
            });
        }
    }
}

TechBlogWeb/Components/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;
        public SideBarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult)View(dataManager.Articles.GetArticles()));
        }
    }
}

TechBlogWeb/Components/TrendVideosViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TechBlogWeb.Components
{
    public class TrendVideosViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TechBlogWeb/Views/Shared/Components/Header/Default.cshtml
@*@model IQueryable<TechBlogWeb.Domain.Entites.Article>*@
@{
	var returnUrl = ViewContext.HttpContext.Request.Path;
}
<header class="tech-header header">
	<div class="container-fluid">
		<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="/"><img src="~/images/version/tech-logo.png" alt=""></a>
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="/">Home</a>
					</li>
					<li class="nav-item dropdown has-submenu menu-large hidden-md-down hidden-sm-down hidden-xs-down">
						<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">News</a>
						<ul class="dropdown-menu megamenu" aria-labelledby="dropdown01">
							<li>
								<div class="container">
									<div class="mega-menu-content clearfix">
										<div class="tab">
											<button class="tablinks active" onclick="openCategory(event, 'cat01')">Car News</button>
											<button class="tablinks" onclick="openCategory(event, 'cat02')">Science</button>
											<button class="tablinks" onclick="openCategory(event, 'cat03')">Social Media</button>
											<button class="tablinks" onclick="openCategory(event, 'cat04')">Technology</button>
											<button class="tablinks" onclick="openCategory(event, 'cat05')">Worldwide</button>
										</div>

										<div class="tab-details clearfix">
											@await Component.InvokeAsync("NewsDrop")
										</div>

									</div>
								</div>
							</li>
						</ul>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Gadgets">Gadgets</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Videos">Videos</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Reviews">Reviews</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="tech-contact.html">Contact Us</a>
					</li>
				</ul>
				<ul class="navbar-nav mr-2">
					@if (User.Identity.IsAuthenticated)
					{
						<li class="nav-item">
							<a class="nav-link" asp-area="User" asp-controller="Profile" asp-action="Index">hi, @User.Identity.Name</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="@returnUrl">LogOut</a>
						</li>
					}
					else
					{
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@returnUrl">Login</a>
						</li>
						<li class="nav-item">
							<div class="nav-link">/</div>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register" asp-route-returnUrl="@returnUrl">Register</a>
						</li>
					}

				</ul>
			</div>
		</nav>
	</div>
</header>