TechBlogWeb/Areas/Admin/Components/NavigatorTagViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechBlogWeb.Domain;

namespace TechBlogWeb.Areas.Admin.Components
{
    public class NavigatorTagViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public NavigatorTagViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            return View(model: dataManager.Articles
                .GetArticles()
                .Select(a => a.Tag)
                .Distinct());
        }
    }
}

TechBlogWeb/Components/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TechBlogWeb.Components
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TechBlogWeb/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TechBlogWeb/Components/MainSectionViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class MainSectionViewComponent : ViewComponent
    {
        readonly DataManager dataManager;
        public MainSectionViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            //Выборка лучших за неделю (in progress)
            var week = DateTime.UtcNow.AddDays(-7);
            var model = dataManager.Articles.GetArticles().Where(a => a.DateTime.CompareTo(week) == 1).ToList();
            return View(model: model);
        }
    }
}

TechBlogWeb/Components/NewsDropViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class NewsDropViewComponent : ViewComponent
    {
        readonly DataManager dataManager;
        public NewsDropViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            var model = dataManager.Articles.GetArticles().OrderBy(a => a.Tag)
                .ThenByDescending(a => a.DateTime);
            return View(model: model);
        }
    }
}

TechBlogWeb/Components/RecentNewsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechBlogWeb.Domain;
using TechBlogWeb.Models;
using TechBlogWeb.Models.ViewModel;

namespace TechBlogWeb.Components
{
    public class RecentNewsViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;
        private int pageSize = 10;

        public RecentNewsViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IViewComponentResult Invoke()
        {
            object articlePage = 1;
            if (Request.RouteValues.ContainsKey("articlePage"))
            {
                Request.RouteValues.TryGetValue("articlePage", out articlePage);
            }
            var aP = int.Parse(articlePage.ToString());
            return View(model: new ArticleListViewModel()
            {
                Articles = dataManager.Articles.GetArticles()
                    .OrderByDescending(a => a.DateTime)
                    .Skip((aP - 1) * pageSize)
                    .Take(10)
                    .ToList(),
                PageInfo = new PageInfo
                {
                    ArticlePerPage = pageSize,
                    CurrentPage = aP,
                    TotalArticle = dataManager.Articles.GetArticles().Count()
                }
            });
        }
    }
}

TechBlogWeb/Components/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechBlogWeb.Domain;
using TechBlogWeb.Domain.Repositories.Abstract;

namespace TechBlogWeb.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;
        public SideBarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult)View(dataManager.Articles.GetArticles()));
        }
    }
}

TechBlogWeb/Components/TrendVideosViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TechBlogWeb.Components
{
    public class TrendVideosViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TechBlogWeb/Views/Home/Components/RecentNews/Default.cshtml
@model ArticleListViewModel
<section class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
				<div class="page-wrapper">
					<div class="blog-top clearfix">
						<h4 class="pull-left">Recent News <a href="#"><i class="fa fa-rss"></i></a></h4>
					</div>

					<div class="blog-list clearfix">
						@for (int i = 0; i < 3; i++)
						{
							<div class="blog-box row">
								<div class="col-md-4">
									<div class="post-media">
										<a href="tech-single.html" title="">
											<img src="~/images/@Model.Articles[i].TitleImagePath" alt="" class="img-fluid">
											<div class="hovereffect"></div>
										</a>
									</div>
								</div>

								<div class="blog-meta big-meta col-md-8">
									<h4><a href="tech-single.html" title="">@Model.Articles[i].Title</a></h4>
									<p>@Model.Articles[i].SubTitle</p>
									<small class="firstsmall"><a class="bg-orange" href="tech-category-01.html" title="">@Model.Articles[i].Tag</a></small>
									<small><a href="tech-single.html" title="">@Model.Articles[i].DateTime</a></small>
									<small><a href="tech-author.html" title="">by @Model.Articles[i].Author</a></small>
									<small><a href="tech-single.html" title=""><i class="fa fa-eye"></i> 1114</a></small>
								</div>
							</div>

							<hr class="invis">
						}

						<div class="row">
							<div class="col-lg-10 offset-lg-1">
								<div class="banner-spot clearfix">
									<div class="banner-img">
										<img src="upload/banner_02.jpg" alt="" class="img-fluid">
									</div>
								</div>
							</div>
						</div>

						<hr class="invis">

						@for (int i = 3; i < Model.Articles.Count; i++)
						{
							<div class="blog-box row">
								<div class="col-md-4">
									<div class="post-media">
										<a href="tech-single.html" title="">
											<img src="~/images/@Model.Articles[i].TitleImagePath" alt="" class="img-fluid">
											<div class="hovereffect"></div>
										</a>
									</div>
								</div>

								<div class="blog-meta big-meta col-md-8">
									<h4><a href="tech-single.html" title="">@Model.Articles[i].Title</a></h4>
									<p>@Model.Articles[i].SubTitle</p>
									<small class="firstsmall"><a class="bg-orange" href="tech-category-01.html" title="">@Model.Articles[i].Tag</a></small>
									<small><a href="tech-single.html" title="">@Model.Articles[i].DateTime</a></small>
									<small><a href="tech-author.html" title="">by @Model.Articles[i].Author</a></small>
									<small><a href="tech-single.html" title=""><i class="fa fa-eye"></i> 1114</a></small>
								</div>
							</div>

							<hr class="invis">
						}

					</div>
				</div>

				<hr class="invis">

				<div class="row">
					<div class="col-md-12">
						<nav aria-label="Page navigation">
							<ul page-model="@Model.PageInfo" 
								page-action="Index"
								class="pagination justify-content-start">
							</ul>
						</nav>
					</div>
				</div>
			</div>
			@* SIDEBAR *@
			@await Component.InvokeAsync("SideBar")
		</div>
	</div>
</section>